modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="emptydark"
version="1.0.0"
displayName="EmptyDark"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="qpnin, MCreator"

[[dependencies.emptydark]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



